config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
   controllers: { 
    registrations: 'registrations',
    sessions: :sessions
   }
  mount ActionCable.server, at: '/cable' 
  root 'toppages#index'
  
  get '/posts/new', to: 'posts#new'
  post '/posts', to: 'posts#create'
  
  resources :users do
    member do
      get :likes
    end
  end
  
  resources :users do
    member do
      get :liked
    end
  end
  
  
  
  resources :users, only: [:show, :index]
  resources :reactions, only: [:create]
  resources :matching, only: [:index]
  resources :rooms, only: [:show]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    after_create_commit { MessageBroadcastJob.perform_later self }
    validates :content, presence: true
    belongs_to :user
    belongs_to :room
    
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :to_user, class_name: "User"
  belongs_to :from_user, class_name: "User"
  enum status: { like: 0, dislike: 1 }
  mount_uploader :profile_image, ProfileImageUploader
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users
  has_many :messages
  has_many :users, through: :room_users
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reactions
  has_many :posts, dependent: :destroy
  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :self_introduction, length: { maximum: 500 }
  enum gender: { man: 0, woman: 1 }
  
  mount_uploader :profile_image, ProfileImageUploader

  
  def update_without_current_password(params, *options)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/matching_controller.rb
class MatchingController < ApplicationController
  before_action :authenticate_user!

  def index
    got_reaction_user_ids = Reaction.where(to_user_id: current_user.id, status: 'like').pluck(:from_user_id).uniq
    @match_users = Reaction.where(to_user_id: got_reaction_user_ids, from_user_id: current_user.id, status: 'like').map(&:to_user)
    @user = User.find(current_user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!
    
    def new
      @post = Post.new
      @user = current_user
    end
    
    def create
      @user = current_user
      if @user.update(image: params[:image])
        redirect_to @user
        flash[:notice] = "投稿が保存されました"
      else
        redirect_to @user
        flash[:alert] = "投稿に失敗しました"
      end
    end

    private
      def post_params
      params.require(:post).permit(:image).merge(user_id: current_user.id)
      end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
   before_action :authenticate_user!
   
  
  # def create
  #   current_user_rooms = RoomUser.where(user_id: current_user.id).map(&:room)
  #   room = RoomUser.where(room: current_user_rooms, user_id: params[:user_id]).map(&:room).first
  #   if room.blank?
  #     room = Room.create
  #     RoomUser.create(room: room, user_id: current_user.id)
  #     RoomUser.create(room: room, user_id: params[:user_id])
  #   end
  #   redirect_to action: :show, id: room.id
  # end

  def show
    # ここでRoom_idを検索する。でも複数のroom_idが出てきてしまうので、ログインしてるユーザーとマッチした相手のroom_idだけを抽出する。
    @room_user_ids = RoomUser.where(user_id: params[:user_id]).pluck(:room_id)
    @me_room_user_ids = RoomUser.where(user_id: current_user.id).pluck(:room_id)
    # @room_userと@me_room_userのかぶってるroom_idが対象のroom_idとなる。
    @room_user = RoomUser.where(room_id: @room_user_ids & @me_room_user_ids)
    @room = Room.find(params[:id])
    #@room_user = @room.room_users.where.not(user_id: current_user.id).first.user
    @messages = Message.where(room: @room).order(:created_at)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  protected

  def after_sign_in_path_for(resource)
    users_path
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
      
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @checked_user_ids = Reaction.where(from_user_id: current_user.id).pluck(:to_user_id)
    users = User.where.not(id: current_user.id)
    @users = users.where.not(id: @checked_user_ids)
    @user = User.find(current_user.id)
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def likes
    @user = User.find(params[:id])
    @liked_users = Reaction.where(from_user_id: current_user.id).where(status: 0)
    @users = User.where(id: @liked_users.pluck(:to_user_id))
  end
  
  def liked
    @user = User.find(params[:id])
    @likes_users = Reaction.where(to_user_id: current_user.id).where(status: 0)
    @users = User.where(id: @likes_users.pluck(:from_user_id))
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matching_helper.rb
module MatchingHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>With</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
    
    
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-light">
  <%= link_to users_path, class: "nav-item nav-link", data: { turbolinks: :false } do %>
    <span class="<%= 'active' if current_page?(users_path) %>">
      <i class="fas fa-home fa-lg inherit"></i>
    </span>
  <% end %>
  <%= link_to likes_user_path(current_user.id), class: "nav-item nav-link" do %>
    <span class="<%= 'active' if current_page?(likes_user_path(current_user.id)) %>">
      <i class="far fa-kiss-wink-heart fa-lg inherit"></i>
    </span>
  <% end %>
  <%= link_to liked_user_path(current_user.id), class: "nav-item nav-link" do %>
    <span class="<%= 'active' if current_page?(liked_user_path(current_user.id)) %>">
      
      <i class="far fa-grin-hearts fa-lg inherit"></i>
    </span>
  <% end %>
  <%= link_to matching_index_path, class: "nav-item nav-link" do %>
    <span class="<%= 'active' if current_page?(matching_index_path) %>">
      <i class="fas fa-comments fa-lg inherit"></i>
    </span>
  <% end %>
  <%= link_to user_path(@user), class: "nav-item nav-link" do %>
    <span class="<%= 'active' if current_page?(user_path(@user)) || current_page?(edit_user_registration_path) %>">
      <i class="fas fa-user fa-lg inherit"></i>
    </span>
  <% end %>
</nav>