config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
   controllers: { 
    registrations: 'registrations',
    sessions: :sessions
   }
  mount ActionCable.server, at: '/cable' 
  root 'toppages#index'
  
  get '/posts/new', to: 'posts#new'
  post '/posts', to: 'posts#create'
  
  resources :users do
    member do
      get :likes
    end
  end
  
  resources :users do
    member do
      get :liked
    end
  end
  
  
  
  resources :users, only: [:show, :index]
  resources :reactions, only: [:create]
  resources :matching, only: [:index]
  resources :rooms, only: [:show]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    after_create_commit { MessageBroadcastJob.perform_later self }
    validates :content, presence: true
    belongs_to :user
    belongs_to :room
    
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :to_user, class_name: "User"
  belongs_to :from_user, class_name: "User"
  enum status: { like: 0, dislike: 1 }
  mount_uploader :profile_image, ProfileImageUploader
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users
  has_many :messages
  has_many :users, through: :room_users
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reactions
  has_many :posts, dependent: :destroy
  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :self_introduction, length: { maximum: 500 }
  enum gender: { man: 0, woman: 1 }
  
  mount_uploader :profile_image, ProfileImageUploader

  
  def update_without_current_password(params, *options)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  # def self.render_with_signed_in_user(user, *args)
  #     ActionController::Renderer::RACK_KEY_TRANSLATION['warden'] ||= 'warden'
  #     proxy = Warden::Proxy.new({}, Warden::Manager.new({})).tap{|i| i.set_user(user, scope: :user) }
  #     renderer = self.renderer.new('warden' => proxy)
  #     renderer.render(*args)
  # end
  
  class << self
    def render_with_signed_in_user(user, *args)
      pp user
      pp args
      
      ActionController::Renderer::RACK_KEY_TRANSLATION['warden'] ||= 'warden'
      proxy = Warden::Proxy.new({}, Warden::Manager.new({})).tap{|i| i.set_user(user, scope: :user) }
      renderer = self.renderer.new('warden' => proxy)
      renderer.render(*args)
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :gender])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :self_introduction, :profile_image])
  end
end

app/controllers/matching_controller.rb
class MatchingController < ApplicationController
  before_action :authenticate_user!

  def index
    got_reaction_user_ids = Reaction.where(to_user_id: current_user.id, status: 'like').pluck(:from_user_id).uniq
    @match_users = Reaction.where(to_user_id: got_reaction_user_ids, from_user_id: current_user.id, status: 'like').map(&:to_user)
    @user = User.find(current_user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!
    
    def new
      @post = Post.new
      @user = current_user
    end
    
    def create
      @user = current_user
      if @user.update(image: params[:image])
        redirect_to @user
        flash[:notice] = "投稿が保存されました"
      else
        redirect_to @user
        flash[:alert] = "投稿に失敗しました"
      end
    end

    private
      def post_params
      params.require(:post).permit(:image).merge(user_id: current_user.id)
      end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  protect_from_forgery :except => [:create]
  def create
    reaction = Reaction.find_or_initialize_by(to_user_id: params[:user_id], from_user_id: current_user.id)
    reaction.update(
      status: params[:reaction]
    )
    # ここでマッチしたらRommUserとRoomを新規作成するメソッドを追加する。
    if Reaction.where(to_user_id: current_user.id, from_user_id: params[:user_id], status: 'like')
      room = Room.create
      RoomUser.create(user_id: current_user.id, room_id: room.id)
      RoomUser.create(user_id: params[:user_id], room_id: room.id)
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end
  
  def after_update_path_for(resource)
    user_path(resource)
  end
  
  def after_sign_up_path_for(resource)
    users_path
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
   before_action :authenticate_user!
   
  
  # def create
  #   current_user_rooms = RoomUser.where(user_id: current_user.id).map(&:room)
  #   room = RoomUser.where(room: current_user_rooms, user_id: params[:user_id]).map(&:room).first
  #   if room.blank?
  #     room = Room.create
  #     RoomUser.create(room: room, user_id: current_user.id)
  #     RoomUser.create(room: room, user_id: params[:user_id])
  #   end
  #   redirect_to action: :show, id: room.id
  # end

  def show
    # ここでRoom_idを検索する。でも複数のroom_idが出てきてしまうので、ログインしてるユーザーとマッチした相手のroom_idだけを抽出する。
    @room_user_ids = RoomUser.where(user_id: params[:user_id]).pluck(:room_id)
    @me_room_user_ids = RoomUser.where(user_id: current_user.id).pluck(:room_id)
    # @room_userと@me_room_userのかぶってるroom_idが対象のroom_idとなる。
    @room_user = RoomUser.where(room_id: @room_user_ids & @me_room_user_ids)
    @room = Room.find(params[:id])
    #@room_user = @room.room_users.where.not(user_id: current_user.id).first.user
    @messages = Message.where(room: @room).order(:created_at)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  protected

  def after_sign_in_path_for(resource)
    users_path
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
      
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @checked_user_ids = Reaction.where(from_user_id: current_user.id).pluck(:to_user_id)
    users = User.where.not(id: current_user.id)
    @users = users.where.not(id: @checked_user_ids)
    @user = User.find(current_user.id)
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def likes
    @user = User.find(params[:id])
    @liked_users = Reaction.where(from_user_id: current_user.id).where(status: 0)
    @users = User.where(id: @liked_users.pluck(:to_user_id))
  end
  
  def liked
    @user = User.find(params[:id])
    @likes_users = Reaction.where(to_user_id: current_user.id).where(status: 0)
    @users = User.where(id: @likes_users.pluck(:from_user_id))
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matching_helper.rb
module MatchingHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/new.html.erb
<div class="text-center">
  <h1>写真を追加</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

  <%= form_for @user, url: posts_path, method: :post do |f| %>
     <% if @user.image? %>
        <%= image_tag @user.image.url %>
     <% else %>
        <%= image_tag "/assets/default.jpg", :size => '100x100' %>
     <% end %>
        <button type="button" class="btn btn-outline-secondary rounded-pill">
           <%= f.file_field :image, accept: 'jpeg gif png' %>
        </button>
　　  <%= f.submit '更新する', class: 'btn btn-primary' %>
  <% end %>

  </div>
</div>

app/views/rooms/show.html.erb
<div class="room-show-page">
  <nav class="navbar navbar-light room__header">
    <%= link_to matching_index_path, class: "nav-item nav-link" do%>
      <i class="fas fa-chevron-left"></i>
    <% end %>

    <div class="room__partner">
      <span class="room__partner-name">
        <%= @room_user.name %>
      </span>
    </div>
  </nav>

  <div id='messages'>
    <%= render @messages %>
  </div>

  <form class="room__message-form">
    <textarea data-behavior="room_speaker" data-room_id="<%= @room.id %>" placeholder="メッセージを入力" class="room__message-form_textarea"></textarea>
  </form>
  
  
</div>

app/views/users/index.html.erb
<div class="user-index-page">
  <%= render "partial/navbar" %>

  <div class="swipe">
    <div class="swipe--status">
      <i class="fa fa-times"></i>
      <i class="fa fa-heart"></i>
    </div>

    <div class="swipe--cards">
      <% @users.each do |user| %>
        <div class="swipe--card" id="<%= user.id %>">
          <% if user.profile_image.url.nil? %>
            
          <% else %>
            <%= image_tag user.profile_image.url, class: "profile-img" %>
          <% end %>
          <p class="profile-name">
            <%= user.name %>
          </p>
        </div>
      <% end %>
      <div class="no-user">近くにお相手がいません</div>
    </div>

    <div class="swipe--buttons">
      <button id="dislike"><i class="fas fa-times fa-2x"></i></button>
      <button id="like"><i class="fas fa-heart fa-2x"></i></button>
    </div>
  </div>

</div>

app/views/users/liked.html.erb
<div class="user-liked-page">
  <%= render "partial/navbar" %>
  <% @users.each do |user|%>
    <% if user.profile_image.url.nil? %>
      <%= user.name %>
    <% else %>
      <%= image_tag user.profile_image.url %>
     <% end %>
    
  <% end %>
</div>

app/views/users/likes.html.erb
<div class="user-likes-page">
  <%= render "partial/navbar" %>
  いいね一覧
  <% @users.each do |user|%>
  
    <%=user.profile_image %>
  
  <% end %>
</div>

app/views/users/show.html.erb
<div class="user-show-page">
  <%= render "partial/navbar" %>
  <div class="profile mt-4">
    <% if @user.profile_image.url.nil? %>
      
    <% else %>
      <%= image_tag @user.profile_image.url, class: "profile-img" %>
    <% end %>
    
    <div class="profile-name mt-4">
      <%= @user.name %>
    </div>
  </div>
  <% if current_user.id == @user.id %>
    <div class="user-action">
      <div class="user-action-common">
        <%= link_to destroy_user_session_path, class: "nav-item nav-link", method: :delete do %>
          <i class="fas fa-sign-out-alt fa-2x"></i>
        <span>ログアウト</span>
        <% end %>
      </div>
      <div class="user-action-common">
        <%= link_to edit_user_registration_path, class: "nav-item nav-link" do %>
          <i class="fas fa-cog fa-2x"></i>
        <span>プロフィール編集</span>
        <% end %>
      </div>
      <div class="user-action-common">
        <%= link_to posts_new_path, class: "nav-item nav-link" do %>
          <i class="fas fa-camera fa-2x"></i>
        <span>写真を追加</span>
        <% end %>
      </div>
    </div>
  <% end %>
</div>